<a href="https://colab.research.google.com/github/RudyHarun99/H8_056/blob/master/04_pytn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

### Import numpy pkg

In [2]:
import numpy as np

### Creating Array

In [3]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [4]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [6]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [7]:
print(np.arange(4))
# (start, stop, step)
print(np.arange(0, 10, 2))

[0 1 2 3]
[0 2 4 6 8]


In [8]:
np.arange(2, 29, 5)

array([ 2,  7, 12, 17, 22, 27])

### Add, Remove, Sort

In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
np.append(arr, [1, 2])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
np.delete(arr, 1)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [13]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

### Shape and Size

In [14]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [15]:
array_example.ndim

3

In [16]:
array_example.size

24

In [17]:
array_example.shape

(3, 2, 4)

In [18]:
arr_one = np.array([[1, 2, 3, 4, 5]])
arr_one.ndim

2

In [19]:
arr_one.size

5

In [20]:
arr_one.shape

(1, 5)

### Reshape

In [21]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [22]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [23]:
a.reshape(6, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

### Convert 1D to 2D

In [24]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)
print(a)

(6,)
[1 2 3 4 5 6]


In [25]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [26]:
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [27]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [28]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [29]:
b = np.expand_dims(a, axis = 1)
b.shape

(6, 1)

In [30]:
c = np.expand_dims(a, axis = 0)
c.shape

(1, 6)

### Indexing and Slicing

In [31]:
data = np.array([1, 2, 3])
print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2])

[1 2 3]
1
2
[1 2]
[2 3]
2


In [32]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
print(a[a >= 5])

[ 5  6  7  8  9 10 11 12]


In [34]:
five_up = (a >= 5)

print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [35]:
divisible_by_2 = a[a % 2 == 0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [36]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


### Creating Array from Existing Data

In [37]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [38]:
a_1 = np.array([[1, 1],
                [2, 2]])

a_2 = np.array([[3, 3],
                [4, 4]])

np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [39]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [40]:
arrsplit = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [41]:
np.hsplit(arrsplit, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [42]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Basic Array Operations

In [45]:
a = np.array([1, 2, 3, 4])
a.sum()

10

In [46]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [47]:
b.sum(axis=0)

array([3, 3])

In [48]:
b.sum(axis=1)

array([2, 4])

In [49]:
data = np.array([1, 2])
ones = np.ones(2)

print(data)
print(ones)

[1 2]
[1. 1.]


In [50]:
print(data + ones)
print(data * data)
print(data / data)
print(data * 2)

[2. 3.]
[1 4]
[1. 1.]
[2 4]


In [51]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [52]:
print(A.sum())
print(A.min())
print(A.min(axis=0))
print(A.max())
print(A.max(axis=1))
print(A.std())

4.8595784
0.05093587
[0.12697628 0.05093587 0.26590556 0.5510652 ]
0.82485143
[0.5510652  0.55645993 0.82485143]
0.21392120766089617


## Matrices

### Creating Matrices

In [53]:
print(np.ones((3, 2)))
print(np.zeros((3, 2)))
print(np.random.random((3, 2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.52939339 0.80613229]
 [0.08596059 0.17043719]
 [0.98012475 0.85376872]]


### Matrix Arithmetic

In [54]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [55]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [56]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [57]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [58]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


### Dot Product
Perkalian Titik antar Matrix

In [59]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [60]:
a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [61]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

### Matrix Indexing

In [62]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0, 1])
print(data[1:3])
print(data[0:2, 1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


### Matrix Aggregation

In [63]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [64]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [65]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


### Transposing and Reshaping

In [66]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [67]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [68]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [69]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
data_col.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [71]:
arr = np.arange(6).reshape((2, 3))
print(arr)

[[0 1 2]
 [3 4 5]]


## N-Dimensional Array

In [72]:
ndarr = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [73]:
print(np.ones((4, 3, 2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [74]:
print(np.zeros((4, 3, 2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [75]:
print(np.random.random((4, 3, 2)))

[[[0.61418041 0.23684592]
  [0.09442972 0.12167006]
  [0.23825778 0.08114212]]

 [[0.20888264 0.15637922]
  [0.26999977 0.83678736]
  [0.20951422 0.0838629 ]]

 [[0.75667389 0.76009302]
  [0.30690498 0.87350969]
  [0.03964835 0.94588435]]

 [[0.21729672 0.10670948]
  [0.15611255 0.8109742 ]
  [0.40274784 0.46465244]]]


### Flatten N-Dimensional Array

In [76]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [77]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])