<a href="https://colab.research.google.com/github/RudyHarun99/H8_056/blob/master/PYTN_Assgn_3_056_Rudy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# BANK MARKETING

## Project Overview

The data is related with direct marketing campaigns of a Portuguese banking institution. The marketing campaigns were based on phone calls. Often, more than one contact to the same client was required, in order to access if the product (bank term deposit) would be ('yes') or not ('no') subscribed.

The classification goal is to predict if the client will subscribe (yes/no) a term deposit (variable y).

## Data Preparation

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [ ]:
path = '/content/gdrive/MyDrive/DATA/Hacktiv8_ptp_python/bank.csv'
df = pd.read_csv(path, sep=';')
df.shape

(4521, 17)

In [ ]:
df.head()

age          job  marital  education  ... pdays  previous poutcome   y
0   30   unemployed  married    primary  ...    -1         0  unknown  no
1   33     services  married  secondary  ...   339         4  failure  no
2   35   management   single   tertiary  ...   330         1  failure  no
3   30   management  married   tertiary  ...    -1         0  unknown  no
4   59  blue-collar  married  secondary  ...    -1         0  unknown  no

[5 rows x 17 columns]

In [ ]:
df.y.value_counts()

no     4000
yes     521
Name: y, dtype: int64

Membuat kolom *target* yang berisi nilai numerikal dari kolom *y* (no = 0, yes = 1)

In [ ]:
df['target'] = df['y'].replace({'no' : 0, 'yes' : 1})
df.head()

age          job  marital  education  ... previous  poutcome   y target
0   30   unemployed  married    primary  ...        0   unknown  no      0
1   33     services  married  secondary  ...        4   failure  no      0
2   35   management   single   tertiary  ...        1   failure  no      0
3   30   management  married   tertiary  ...        0   unknown  no      0
4   59  blue-collar  married  secondary  ...        0   unknown  no      0

[5 rows x 18 columns]

In [ ]:
df.target.value_counts()

0    4000
1     521
Name: target, dtype: int64

Cek apakah ada nilai null?

In [ ]:
print(df.isnull().sum(), '\n')

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
target       0
dtype: int64 



In [ ]:
y = pd.DataFrame(df.target)
y.head()

target
0       0
1       0
2       0
3       0
4       0

Mengubah nilai-nilai kategorikal menjadi nilai-nilai numerikal menggunakan **pd.get_dummies**

In [ ]:
X = pd.get_dummies(df.drop(['y', 'target'], axis = 1))
X.head()

age  balance  day  ...  poutcome_other  poutcome_success  poutcome_unknown
0   30     1787   19  ...               0                 0                 1
1   33     4789   11  ...               0                 0                 0
2   35     1350   16  ...               0                 0                 0
3   30     1476    3  ...               0                 0                 1
4   59        0    5  ...               0                 0                 1

[5 rows x 51 columns]

In [ ]:
X.shape

(4521, 51)

Membuat set test dan train dari *y* dan *X*, dimana komposisi test sebesar 20% dan train sebesar 80%

In [ ]:
from sklearn.model_selection import train_test_split as tts
Xtr, Xts, ytr, yts = tts(X, y, test_size = .2)

Import package untuk membuat model

In [ ]:
from sklearn.linear_model import LogisticRegression as lr
from sklearn.tree import DecisionTreeClassifier as dt
from sklearn.ensemble import RandomForestClassifier as rf
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB as gb
from sklearn.neighbors import KNeighborsClassifier as kn

Import package untuk membuat metrics

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

## Logistic Regression

In [ ]:
LR = lr(solver='lbfgs', max_iter=10000)
LR.fit(Xtr, ytr)
predLR = LR.predict(Xts)
accLR = accuracy_score(yts, predLR)
matrixLR = confusion_matrix(yts, predLR)
print(accLR)
print(matrixLR)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.8928176795580111
[[777  18]
 [ 79  31]]


## Decision Tree

In [ ]:
DT = dt()
DT.fit(Xtr, ytr)
predDT = DT.predict(Xts)
accDT = accuracy_score(yts, predDT)
matrixDT = confusion_matrix(yts, predDT)
print(accDT)
print(matrixDT)

0.8696132596685083
[[739  56]
 [ 62  48]]


## Random Forest

In [ ]:
RF = rf()
RF.fit(Xtr, ytr)
predRF = RF.predict(Xts)
accRF = accuracy_score(yts, predRF)
matrixRF = confusion_matrix(yts, predRF)
print(accRF)
print(matrixRF)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


0.8917127071823204
[[778  17]
 [ 81  29]]


## Support Vector Machine

In [ ]:
SVM = SVC()
SVM.fit(Xtr, ytr)
predSVM = SVM.predict(Xts)
accSVM = accuracy_score(yts, predSVM)
matrixSVM = confusion_matrix(yts, predSVM)
print(accSVM)
print(matrixSVM)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.8784530386740331
[[795   0]
 [110   0]]


## Naive Bayes

In [ ]:
GB = gb()
GB.fit(Xtr, ytr)
predGB = GB.predict(Xts)
accGB = accuracy_score(yts, predGB)
matrixGB = confusion_matrix(yts, predGB)
print(accGB)
print(matrixGB)

0.825414364640884
[[697  98]
 [ 60  50]]


/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


## K-Nearest Neighbors

In [ ]:
KN = kn()
KN.fit(Xtr, ytr)
predKN = LR.predict(Xts)
accKN = accuracy_score(yts, predKN)
matrixKN = confusion_matrix(yts, predKN)
print(accKN)
print(matrixKN)

0.8928176795580111
[[777  18]
 [ 79  31]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  


## Accuracy Score

In [ ]:
print('Logistic Regression    :', accLR)
print('Decision Tree          :', accDT)
print('Random Forest          :', accRF)
print('Support Vector Machine :', accSVM)
print('Naive Bayes            :', accGB)
print('K Nearest Neighbors    :', accKN)

Logistic Regression    : 0.8928176795580111
Decision Tree          : 0.8696132596685083
Random Forest          : 0.8917127071823204
Support Vector Machine : 0.8784530386740331
Naive Bayes            : 0.825414364640884
K Nearest Neighbors    : 0.8928176795580111
